# .air.toml
# Config file for air: https://github.com/cosmtrek/air

# Working directory
root = "."
tmp_dir = "tmp"

[build]
# Command to build the binary
cmd = "go build -o ./tmp/main ./cmd/server"
# The binary to run
bin = "./tmp/main"

# Customize the watching process
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor"]

# Log name
log = "air-log.log"
# Delay in milliseconds before restarting
delay = 1000 # 1s

[log]
# Show log time
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
